// Copyright © 2018 evaluni. All rights reserved.

// This line must be included eve if not needed, or the Swift compiler would silently crash.
#import <Foundation/Foundation.h>

// Those headers generated by "castify-headers"
#import "runtime.h"
#import "net_encoder.h"
#import "net_decoder.h"
#import "publisher.h"

FOUNDATION_EXPORT double CastifyVersionNumber;

FOUNDATION_EXPORT const unsigned char CastifyVersionString[];

