// Copyright © 2019 Castify Inc. All rights reserved.

// Those headers generated by "castify-headers"
#import "runtime.h"
#import "broadcaster.h"
#import "player.h"
#import "publisher.h"

FOUNDATION_EXPORT double CastifyVersionNumber;

FOUNDATION_EXPORT const unsigned char CastifyVersionString[];
