// Copyright © 2019 Castify Inc. All rights reserved.

// This line must be included eve if not needed, or the Swift compiler would silently crash.
#import <Foundation/Foundation.h>

// Those headers generated by "castify-headers"
#import "runtime.h"
#import "broadcaster.h"
#import "player.h"
#import "publisher.h"

FOUNDATION_EXPORT double CastifyVersionNumber;

FOUNDATION_EXPORT const unsigned char CastifyVersionString[];

